### ISSUE TITLE
Shape error during training.

### ISSUE THREAD

**Issue by ArkadeepAcharya** [kyegomez/phi-1#2]
I am getting the following error while running train_distributed.py after using accelerate launch and the configs as mentioned in the repo.

RuntimeError: Cannot writeback when the parameter shape changes
Expects torch.Size([8192896]) but got torch.Size([64007, 128])

Can anyone please suggest me the solution.

**Comment by kyegomez** [comment]
@ArkadeepAcharya 

Hey,  I have fixed the shape error during training. The error was occurring due to a parameter shape mismatch. I have corrected the shape to match the expected size.

Thank you for bringing this to my attention. Let me know if you have any further issues.

**Comment by ArkadeepAcharya** [comment]
Thank you for your response!.
Can you please provide a detailed explanation about how I can run the train.py. I have access to a linux server with Tesla V100-PCIE-32GB GPUs but I am unable to get the train.py started. 
I am frequently getting error as 
"TimeoutError: The client socket has timed out after 1800s while trying to connect to .."

Any kind of help would be appreciated.
Thanks!
